---
version: 3

dependencies:
  galaxy:
    collections:
      - name: dellemc.openmanage
        version: ">=9.0.0,<10.0.0"
      - name: ansible.posix
  python:
    - omsdk
  system: []

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

additional_build_steps:
  append_galaxy:
    - RUN truncate -s 0 /usr/share/ansible/collections/ansible_collections/dellemc/openmanage/bindep.txt || true
